import { StyleSheet } from "react-native";

export const profilestyle = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FFFFFF",
    },
    scrollContainer: {
        paddingBottom: 80,
    },
    profileHeader: {
        alignItems: 'center',
        paddingTop: 40,
        paddingBottom: 30,
        backgroundColor: '#7a0f0fff',
    },
    avatarContainer: {
        position: 'relative',
        marginBottom: 16,
    },
    avatarImage: {
        width: 90,
        height: 90,
        borderRadius: 45,
        borderWidth: 3,
        borderColor: '#fff',
        backgroundColor: '#fff',
    },
    avatar: {
        fontSize: 90,
    },
    editIcon: {
        position: 'absolute',
        bottom: -5,
        right: -5,
        backgroundColor: '#fff',
        borderRadius: 18,
        padding: 8,
        borderWidth: 2,
        borderColor: '#dc2626',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
    },
    editIconText: {
        fontSize: 16,
    },
    name: {
        fontSize: 24,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 6,
    },
    email: {
        fontSize: 14,
        color: '#fff',
        opacity: 0.9,
    },
    infoCard: {
        backgroundColor: '#fff',
        paddingTop: 20,
        paddingBottom: 10,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginLeft: 8,
    },
    infoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 20,
    },
    passwordItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 20,
    },
    icon: {
        fontSize: 22,
        marginRight: 16,
        width: 24,
        textAlign: 'center',
    },
    infoText: {
        fontSize: 15,
        color: '#1F2937',
        marginLeft: 0,
    },
    infoLabel: {
        fontSize: 15,
        color: '#6B7280',
        flex: 1,
    },
    passwordText: {
        fontSize: 15,
        color: '#1F2937',
        letterSpacing: 2,
    },
    statusBadge: {
        backgroundColor: '#D1FAE5',
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 16,
    },
    statusText: {
        color: '#059669',
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'capitalize',
    },
    trackingBadge: {
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 16,
    },
    trackingOnBadge: {
        backgroundColor: '#D1FAE5',
    },
    trackingOffBadge: {
        backgroundColor: '#FEE2E2',
    },
    trackingText: {
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
    },
    actionButtons: {
        paddingHorizontal: 16,
        marginTop: 20,
        marginBottom: 20,
    },
    primaryButton: {
        backgroundColor: '#7a0f0fff',
        paddingVertical: 16,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    secondaryButton: {
        backgroundColor: '#1F2937',
        paddingVertical: 16,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    primaryButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
        marginLeft: 8,
    },
    secondaryButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
        marginLeft: 8,
    },

    modalContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
        width: "90%",
        backgroundColor: "#fff",
        padding: 24,
        borderRadius: 16,
        alignItems: "center",
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: "700",
        marginBottom: 8,
        color: '#1F2937',
        textAlign: 'center',
    },
     modalSubtitle: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 24,
        paddingHorizontal: 10,
    },
    input: {
        flex: 1,
        height: 50,
        fontSize: 15,
        color: '#374151',
    },
    inputContainer: {
        width: '100%',
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 8,
        color: '#374151',
    },
    passwordInputContainer: {
        flexDirection: "row",
        alignItems: 'center',
        width: '100%',
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 10,
        paddingLeft: 14,
        height: 50,
        backgroundColor: '#F9FAFB'
    },

    inputError: {
        borderColor: '#dc2626', 
    },
    errorText: {
        color: "#dc2626",
        fontSize: 12,
        alignSelf: 'flex-start',
        marginTop: 4,
        marginBottom: 12,
    },
    modalButtonContainer: {
        flexDirection: "row",
        marginTop: 24,
        width: "100%",
        gap: 12,
    },
    saveButton: {
        backgroundColor: "#219352ff",
        padding: 14,
        borderRadius: 10,
        flex: 1,
        alignItems: "center",
        justifyContent: 'center',
    },
     disabledButton: {
        opacity: 0.7,
    },
    cancelButton: {
        backgroundColor: "#dc2626",
        padding: 14,
        borderRadius: 10,
        flex: 1,
         alignItems: "center",
        justifyContent: 'center',
        borderColor: '#D1D5DB'
    },
    cancelButtonText: {
        color: '#ffffffff',
        fontWeight: '600',
        fontSize: 15,
    },
    buttonText: {
        color: 'white',
        fontWeight: '600',
        fontSize: 15,
    },
    
    toggleButton: {
        padding: 10,
    },
    modalAvatarPreview: {
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 12,
        backgroundColor: '#F3F4F6',
        borderWidth: 3,
        borderColor: '#E5E7EB',
    },
    changePhotoButton: {
        marginTop: 8,
        backgroundColor: '#F3F4F6',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#D1D5DB',
    },
    changePhotoButtonText: {
        color: '#374151',
        fontSize: 14,
        fontWeight: '600',
    },
    otpSubtitle: {
        fontSize: 15,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 24,
    },
    otpInput: {
        width: '80%',
        borderWidth: 1,
        borderColor: '#D1D5DB',
        padding: 14,
        borderRadius: 10,
        fontSize: 18,
        color: '#374151',
        textAlign: 'center',
        letterSpacing: 8,
        marginBottom: 16,
    },

    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',      
        marginBottom: 8,      
        alignSelf: 'flex-start', 
    },
});